# GoReleaser configuration for homelabctl
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: homelabctl
    binary: homelabctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    mod_timestamp: "{{.CommitTimestamp}}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactors
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: monkeymonk
    name: homelabctl
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## homelabctl {{ .Tag }}

    **Full Changelog**: https://github.com/monkeymonk/homelabctl/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    ```bash
    # Linux AMD64
    curl -LO https://github.com/monkeymonk/homelabctl/releases/download/{{ .Tag }}/homelabctl_{{ .Version }}_linux_x86_64.tar.gz
    tar xzf homelabctl_{{ .Version }}_linux_x86_64.tar.gz
    sudo mv homelabctl /usr/local/bin/

    # macOS ARM64 (Apple Silicon)
    curl -LO https://github.com/monkeymonk/homelabctl/releases/download/{{ .Tag }}/homelabctl_{{ .Version }}_darwin_arm64.tar.gz
    tar xzf homelabctl_{{ .Version }}_darwin_arm64.tar.gz
    sudo mv homelabctl /usr/local/bin/

    # Or via go install
    go install github.com/monkeymonk/homelabctl@{{ .Tag }}
    ```

# Homebrew tap (optional - configure after creating tap repo)
brews:
  - repository:
      owner: monkeymonk
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/monkeymonk/homelabctl
    description: CLI tool for managing declarative Docker stacks in your homelab
    license: MIT
    test: |
      system "#{bin}/homelabctl --help"
    install: |
      bin.install "homelabctl"

# Docker images (optional)
dockers:
  - image_templates:
      - "ghcr.io/monkeymonk/homelabctl:{{ .Tag }}"
      - "ghcr.io/monkeymonk/homelabctl:v{{ .Major }}"
      - "ghcr.io/monkeymonk/homelabctl:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/monkeymonk/homelabctl:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

# AUR package (Arch Linux - optional)
aurs:
  - name: homelabctl-bin
    homepage: https://github.com/monkeymonk/homelabctl
    description: CLI tool for managing declarative Docker stacks in your homelab
    maintainers:
      - "Your Name <your.email@example.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/homelabctl-bin.git"
    package: |-
      # bin
      install -Dm755 "./homelabctl" "${pkgdir}/usr/bin/homelabctl"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/homelabctl/LICENSE"

      # completions (if added later)
      # install -Dm644 "./completions/bash" "${pkgdir}/usr/share/bash-completion/completions/homelabctl"
      # install -Dm644 "./completions/zsh" "${pkgdir}/usr/share/zsh/site-functions/_homelabctl"
      # install -Dm644 "./completions/fish" "${pkgdir}/usr/share/fish/vendor_completions.d/homelabctl.fish"

announce:
  skip: "{{gt .Patch 0}}"  # Only announce major/minor releases
